nodeLinker: node-modules

# Путь к папке с кешем
cacheFolder: .yarn/cache

# Сжатие кеша
compressionLevel: mixed

# Поддержка старых пакетов
packageExtensions:
  "next@*":
    dependencies:
      "react-dom": "*"
      "react": "*"